---
apiVersion: batch/v1
kind: Job
metadata:
  name: splitnn-datasource
  namespace: sparse
  labels:
    app: splitnn-datasource
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - datasource
                - aio
              - key: kubernetes.io/arch
                operator: In
                values:
                - "amd64"
      containers:
      - name: splitnn-datasource
        image: anterondocker/splitnn:pytorch
        imagePullPolicy: IfNotPresent
        env:
        - name: MASTER_UPSTREAM_HOST
          value: "$SPARSE_DATASOURCE_DOWNSTREAM_HOST"
        - name: MASTER_UPSTREAM_PORT
          value: "$SPARSE_DATASOURCE_DOWNSTREAM_PORT"
        command: ["python3"]
        args:
        - "datasource.py"
        - "--no-datasources"
        - "$SPARSE_NO_DATASOURCES"
        - "--model"
        - "$SPARSE_MODEL"
        - "--dataset"
        - "$SPARSE_DATASET"
        - "--no-samples"
        - "$SPARSE_NO_SAMPLES"
        - "--use-scheduling"
        - "$SPARSE_USE_SCHEDULING"
        - "--target-latency"
        - "$SPARSE_TARGET_LATENCY"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
        - name: sparse-stats
          mountPath: /data/stats
      restartPolicy: Never
      volumes:
      - name: app-code
        hostPath:
          path: /opt/splitnn
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
      - name: sparse-stats
        hostPath:
          path: /var/lib/sparse/stats
