---
apiVersion: v1
kind: Service
metadata:
  name: splitnn-worker
  namespace: sparse
  labels:
    app: splitnn-worker
spec:
  type: NodePort
  ports:
  - port: 50007
    targetPort: 50007
    nodePort: $SPARSE_DATASOURCE_DOWNSTREAM_PORT
  selector:
    app: splitnn-worker

